### ISSUE TITLE
[common] Создать в репозитории подпапки для отдельных частей проекта

### ISSUE THREAD

**Issue by kofes** [TwistRU/ShopLab#1]
В корне репозитория создать следующие папки:
- для бэкенда создать папку `backend`
- для фронтенда создать папку `frontend`

В дальнейшем весь код проекта будет заливаться в те папки, к которым относится написанный код

**Comment by Chelove4ik** [comment]
Fixed with commit f1b1ca76e6c83a61f55fdbcfd80fff818147852a
